language: ruby
rvm:
  - "2.1.4"
addons:
  postgresql: "9.3"
services:
  - postgresql
before_script:
  - psql -c 'create database task_manager_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
install:
  - bundle install